environments:
    - name:
      configs:
          endpoints:
              production:
              sandbox:
          security:
              enabled:
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal:
                deploymentEnvironment:
                deploymentVhost:
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:

